server {
    listen 80;

    location /api/ {
        proxy_pass http://varroda-api:5050/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }

    location /videos/ {
        root /usr/share/nginx/html;
        add_header Accept-Ranges bytes;
        add_header Cache-Control "public, max-age=86400";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
